# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional

__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "7be0d9fbff18f68deb73b37c48bf8aafa6033529 *"
__dependency_versions__: Dict[str, Optional[str]] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
