# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional


__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "dd0e7174f41428929c2217c6516115fc62e93222 *"
__dependency_versions__: Dict[str, Optional[str]] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
