name: Build Rucio/Butler ingestd container
on:
  push:
    tags:
    - v*
  pull_request:

env:
  INGESTD_NAME: ctrl_ingestd

jobs:
  build:
    using: "composite"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Define the tag
      id: tag
      shell: bash
      run: echo "tag=`bash ${GITHUB_ACTION_PATH}/docker-tag.sh`" >> ${GITHUB_OUTPUT}

    - name: Build ingest image
      working-directory: docker
      run: |
        docker-compose -f "docker-compose.yml" --env-file ingestd.env build ingestd

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: |
        INGESTD_ID=ghcr.io/${{ github.repository_owner }}/$INGESTD_NAME

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo INGESTD_ID=$INGESTD_ID
        echo VERSION=$VERSION
        echo TAG=${{ steps.tag.outputs.tag }}
        docker tag $INGESTD_NAME $INGESTD_ID:$TAG
        docker push $INGESTD_ID:$TAG
